import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { Toaster } from '@/components/ui/sonner';
import { AuthProvider } from '@descope/nextjs-sdk';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: {
		default: 'Next Dashboard | Zulmy Azhary',
		template: 'Next Dashboard | %s',
	},
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<AuthProvider projectId="P2ndvInMTyqm8dOe7vJsgcwtDFKV">
			<html lang="en">
				<body className={inter.className}>
					<Toaster position="bottom-left" richColors theme="light" />
					{children}
				</body>
			</html>
		</AuthProvider>
	);
}
